package:
  name: circexplorer2
  version: "2.2.2"

source:
  fn: CIRCexplorer2-2.2.2.tar.gz
  url: https://pypi.python.org/packages/83/7c/3f7deb091156d8bf531f19ec907fd759c2a9771108ef9266dbb9ba0174a9/CIRCexplorer2-2.2.2.tar.gz
  md5: 7dd94685b0c7e24bca9eea335aa8beb2

build:
  entry_points:
    - CIRCexplorer2=circ2.command_parse:main
    - fetch_ucsc.py=circ2.fetch_ucsc:main
    - fast_circ.py=circ2.fast_circ:main
  number: 0
  skip: True  # [not py27]

requirements:
  build:
    - python
    - pysam >=0.8.4
    - pybedtools
    - docopt
    - scipy
    - tophat
    - cufflinks
    - bedtools
    - ucsc-genepredtogtf
    - ucsc-gtftogenepred
    - ucsc-bedgraphtobigwig
    - ucsc-bedtobigbed

  run:
    - python
    - pysam >=0.8.4
    - pybedtools
    - docopt
    - scipy
    - tophat
    - cufflinks
    - bedtools
    - ucsc-genepredtogtf
    - ucsc-gtftogenepred
    - ucsc-bedgraphtobigwig
    - ucsc-bedtobigbed

test:
  imports:
    - circ2.align
    - circ2.parse
    - circ2.annotate
    - circ2.assemble
    - circ2.denovo

about:
  home: https://github.com/YangLab/CIRCexplorer2
  license: MIT License
  summary: 'Circular RNA analysis toolkits'
