package:
  name: gseapy
  version: "0.5.2a0"

source:
  fn: gseapy-0.5.2a0.zip
  url: https://pypi.python.org/packages/2b/36/379552c32b9da984b3420a6a38bcd88c68313e955573425044766f58dd76/gseapy-0.5.2a0.zip
  md5: 0bef5b8b2eb4ba0c2c542c0d72e123ab
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - gseapy = gseapy:main
    #
    # Would create an entry point called gseapy that calls gseapy.main()

    - gseapy = gseapy.__main__:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.8.0
    - pandas >=0.16
    - matplotlib >=1.4.3
    - beautifulsoup4 >=4.4.1
    - requests

  run:
    - python
    - numpy >=1.8.0
    - pandas >=0.16
    - matplotlib >=1.4.3
    - beautifulsoup4 >=4.4.1
    - requests

test:
  # Python imports
  imports:
    - gseapy

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - gseapy --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/BioNinja/gseapy
  license: MIT License
  summary: 'Gene Set Enrichment Analysis in Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
