about:
  home: https://github.com/rodrigofaccioli/2pg_cartesian
  license_file: LICENSE
  summary: 2pg cartesian is a framework of optimization algorithms for protein structure prediction.

package:
  name: 2pg_cartesian
  version: 1.0

build:
  number: 0

source:
  fn: v1.0.tar.gz
  url: https://github.com/rodrigofaccioli/2pg_cartesian/archive/v1.0.tar.gz
  md5: e0485b1b37a03d6601bcaae78954fff4

requirements:
  build:
    - gcc  # [linux]
    - llvm  # [osx]
    - cmake
  run:
    - libgcc  # [linux]

test:
  commands:
    - 