about:
  home: https://github.com/rodrigofaccioli/2pg_cartesian
  license_file: LICENSE
  summary: 2pg cartesian is a framework of optimization algorithms for protein structure prediction.

package:
  name: 2pg_cartesian
  version: 1.0

build:
  number: 0

source:
  fn: v1.0.tar.gz
  url: https://github.com/rodrigofaccioli/2pg_cartesian/archive/v1.0.tar.gz
  md5: 80db122d31c5a8481dc36f303e9edc05

requirements:
  build:
    - gcc  # [linux]
    - llvm  # [osx]
    - cmake
  run:
    - libgcc  # [linux]
    - gromacs

test:
  commands:
    - protpred-Gromacs-Test_random_number